<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'assoconnect_graphql_mutation_validator.validator' shared service.

include_once $this->targetDirs[3].'/vendor/assoconnect/graphql-mutation-validator-bundle/Validator/MutationValidator.php';

return $this->services['assoconnect_graphql_mutation_validator.validator'] = new \AssoConnect\GraphQLMutationValidatorBundle\Validator\MutationValidator(($this->services['validator'] ?? $this->getValidatorService()));
