<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.command.dump_schema' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Command/RequestExecutorLazyLoaderTrait.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Command/GraphQLDumpSchemaCommand.php';

$this->services['overblog_graphql.command.dump_schema'] = $instance = new \Overblog\GraphQLBundle\Command\GraphQLDumpSchemaCommand(($this->targetDirs[3].'/src'));

$instance->setRequestExecutorFactory([0 => [0 => $this, 1 => 'get'], 1 => [0 => 'overblog_graphql.request_executor']]);

return $instance;
