<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.controller.graphql' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Controller/GraphController.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Request/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Request/UploadParserTrait.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Request/BatchParser.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Request/Parser.php';

return $this->services['overblog_graphql.controller.graphql'] = new \Overblog\GraphQLBundle\Controller\GraphController(new \Overblog\GraphQLBundle\Request\BatchParser(), ($this->services['overblog_graphql.request_executor'] ?? $this->load('getOverblogGraphql_RequestExecutorService.php')), ($this->services['overblog_graphql.request_parser'] ?? ($this->services['overblog_graphql.request_parser'] = new \Overblog\GraphQLBundle\Request\Parser())), true, 'relay');
