<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.request_executor' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Request/Executor.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Executor/ExecutorInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Executor/Executor.php';
include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Type/Schema.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Builder/SchemaBuilder.php';
include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Executor/Promise/PromiseAdapter.php';
include_once $this->targetDirs[3].'/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php';

$this->services['overblog_graphql.request_executor'] = $instance = new \Overblog\GraphQLBundle\Request\Executor(new \Overblog\GraphQLBundle\Executor\Executor(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['overblog_graphql.promise_adapter.default'] ?? ($this->privates['overblog_graphql.promise_adapter.default'] = new \GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter())), $this->parameters['overblog_graphql.default_resolver']);

$instance->setMaxQueryComplexity(false);
$instance->setMaxQueryDepth(false);
$instance->addSchema('default', (new \Overblog\GraphQLBundle\Definition\Builder\SchemaBuilder(($this->services['overblog_graphql.type_resolver'] ?? $this->load('getOverblogGraphql_TypeResolverService.php')), true))->create('Query', 'Mutation', NULL, [], []));
$instance->enableIntrospectionQuery();

return $instance;
