<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'phpexcel' shared service.

include_once $this->targetDirs[3].'/vendor/onurb/excel-bundle/lib/ExcelBundle/Factory/CompatibilityFactory.php';
include_once $this->targetDirs[3].'/vendor/onurb/excel-bundle/lib/ExcelBundle/Factory/ExcelFactory.php';

return $this->services['phpexcel'] = new \Onurb\Bundle\ExcelBundle\Factory\CompatibilityFactory(($this->services['phpspreadsheet'] ?? ($this->services['phpspreadsheet'] = new \Onurb\Bundle\ExcelBundle\Factory\ExcelFactory())));
