<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tags extends \App\Entity\Tags implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test1', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'guid', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test2', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test3'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test1', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'guid', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test2', '' . "\0" . 'App\\Entity\\Tags' . "\0" . 'test3'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tags $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTest(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest', []);

        return parent::getTest();
    }

    /**
     * {@inheritDoc}
     */
    public function setTest(?array $test): \App\Entity\Tags
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest', [$test]);

        return parent::setTest($test);
    }

    /**
     * {@inheritDoc}
     */
    public function getTest1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest1', []);

        return parent::getTest1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTest1($test1): \App\Entity\Tags
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest1', [$test1]);

        return parent::setTest1($test1);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuid', []);

        return parent::getGuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuid(?string $guid): \App\Entity\Tags
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuid', [$guid]);

        return parent::setGuid($guid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTest2(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest2', []);

        return parent::getTest2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTest2(?array $test2): \App\Entity\Tags
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest2', [$test2]);

        return parent::setTest2($test2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTest3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest3', []);

        return parent::getTest3();
    }

    /**
     * {@inheritDoc}
     */
    public function setTest3($test3): \App\Entity\Tags
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest3', [$test3]);

        return parent::setTest3($test3);
    }

}
