<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \App\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'person', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'zip', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'region_id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'house', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'corp', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'level', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'flat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'person', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'zip', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'region_id', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'house', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'corp', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'level', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Address' . "\0" . 'flat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTimeInterface $created): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\App\Entity\Orders $order): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\App\Entity\Orders $order): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(?\App\Entity\Users $user_id): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$user_id]);

        return parent::setUserId($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', []);

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(?string $person): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', [$person]);

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip(?string $zip): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionId', []);

        return parent::getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegionId(?int $region_id): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegionId', [$region_id]);

        return parent::setRegionId($region_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(?string $city): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet(?string $street): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getHouse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHouse', []);

        return parent::getHouse();
    }

    /**
     * {@inheritDoc}
     */
    public function setHouse(?string $house): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHouse', [$house]);

        return parent::setHouse($house);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorp', []);

        return parent::getCorp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorp(?string $corp): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorp', [$corp]);

        return parent::setCorp($corp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(?string $level): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment(?string $comment): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?bool $active): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getFlat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlat', []);

        return parent::getFlat();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlat(?string $flat): \App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlat', [$flat]);

        return parent::setFlat($flat);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($key, $value = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$key, $value]);

        return parent::setData($key, $value);
    }

}
