<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductItem extends \App\Entity\ProductItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'created', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'name', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'product_id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'basketItems', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'productItemImages', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'entity', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'status', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'avarda_id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'importRelations', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'price', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'orderItems'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'created', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'name', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'product_id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'basketItems', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'productItemImages', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'entity', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'status', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'avarda_id', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'importRelations', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'price', '' . "\0" . 'App\\Entity\\ProductItem' . "\0" . 'orderItems'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTimeInterface $created): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductId(\App\Entity\Product $productId): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductId', [$productId]);

        return parent::addProductId($productId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductId(\App\Entity\Product $productId): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductId', [$productId]);

        return parent::removeProductId($productId);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getBasketItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBasketItems', []);

        return parent::getBasketItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addBasketItem(\App\Entity\BasketItem $basketItem): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBasketItem', [$basketItem]);

        return parent::addBasketItem($basketItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBasketItem(\App\Entity\BasketItem $basketItem): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBasketItem', [$basketItem]);

        return parent::removeBasketItem($basketItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductItemImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductItemImages', []);

        return parent::getProductItemImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductItemImage(\App\Entity\ProductItemImage $productItemImage): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductItemImage', [$productItemImage]);

        return parent::addProductItemImage($productItemImage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductItemImage(\App\Entity\ProductItemImage $productItemImage): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductItemImage', [$productItemImage]);

        return parent::removeProductItemImage($productItemImage);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile($image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity(): ?\App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', []);

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntity(?\App\Entity\Product $entity): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntity', [$entity]);

        return parent::setEntity($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvardaId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvardaId', []);

        return parent::getAvardaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvardaId(?int $avarda_id): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvardaId', [$avarda_id]);

        return parent::setAvardaId($avarda_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportRelations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportRelations', []);

        return parent::getImportRelations();
    }

    /**
     * {@inheritDoc}
     */
    public function addImportRelation(\App\Entity\ImportRelation $importRelation): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImportRelation', [$importRelation]);

        return parent::addImportRelation($importRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImportRelation(\App\Entity\ImportRelation $importRelation): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImportRelation', [$importRelation]);

        return parent::removeImportRelation($importRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(?float $price): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', []);

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItem(\App\Entity\OrderItem $orderItem): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItem', [$orderItem]);

        return parent::addOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderItem(\App\Entity\OrderItem $orderItem): \App\Entity\ProductItem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderItem', [$orderItem]);

        return parent::removeOrderItem($orderItem);
    }

}
