<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'catalogs', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productUrls', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productTags', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'producttagitem', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'tagsArray', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'allTagsArray'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'catalogs', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productUrls', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productItems', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'productTags', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'producttagitem', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'tagsArray', '' . "\0" . 'App\\Entity\\Product' . "\0" . 'allTagsArray'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible(?bool $visible): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTimeInterface $created): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(\DateTimeInterface $updated): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatalogs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatalogs', []);

        return parent::getCatalogs();
    }

    /**
     * {@inheritDoc}
     */
    public function addCatalog(\App\Entity\Catalog $catalog): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCatalog', [$catalog]);

        return parent::addCatalog($catalog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCatalog(\App\Entity\Catalog $catalog): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCatalog', [$catalog]);

        return parent::removeCatalog($catalog);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductUrls(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductUrls', []);

        return parent::getProductUrls();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductUrl(\App\Entity\ProductUrl $productUrl): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductUrl', [$productUrl]);

        return parent::addProductUrl($productUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductUrl(\App\Entity\ProductUrl $productUrl): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductUrl', [$productUrl]);

        return parent::removeProductUrl($productUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductItems', []);

        return parent::getProductItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductItem(\App\Entity\ProductItem $productItem): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductItem', [$productItem]);

        return parent::addProductItem($productItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductItem(\App\Entity\ProductItem $productItem): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductItem', [$productItem]);

        return parent::removeProductItem($productItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTags(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTags', []);

        return parent::getProductTags();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductTag(\App\Entity\ProductTag $productTag): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductTag', [$productTag]);

        return parent::addProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductTag(\App\Entity\ProductTag $productTag): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductTag', [$productTag]);

        return parent::removeProductTag($productTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducttagitem(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducttagitem', []);

        return parent::getProducttagitem();
    }

    /**
     * {@inheritDoc}
     */
    public function addProducttagitem(\App\Entity\ProductTagItem $producttagitem): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProducttagitem', [$producttagitem]);

        return parent::addProducttagitem($producttagitem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProducttagitem(\App\Entity\ProductTagItem $producttagitem): \App\Entity\Product
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProducttagitem', [$producttagitem]);

        return parent::removeProducttagitem($producttagitem);
    }

    /**
     * {@inheritDoc}
     */
    public function setTagsArray(array $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTagsArray', [$tags]);

        return parent::setTagsArray($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTagsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagsArray', []);

        return parent::getTagsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllTagsArray(array $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllTagsArray', [$tags]);

        return parent::setAllTagsArray($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllTagsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllTagsArray', []);

        return parent::getAllTagsArray();
    }

}
