<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5IVKRU1' shared service.

return $this->privates['.service_locator.5IVKRU1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['args' => function (): \Overblog\GraphQLBundle\Definition\Argument {
    return ($this->privates['.errored..service_locator.5IVKRU1.Overblog\GraphQLBundle\Definition\Argument'] ?? $this->load('getArgumentService.php'));
}]);
