<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assoconnect_graphql_mutation_validator.formatter' shared service.

include_once $this->targetDirs[3].'/vendor/assoconnect/graphql-mutation-validator-bundle/Formatter/Formatter.php';

return $this->privates['assoconnect_graphql_mutation_validator.formatter'] = new \AssoConnect\GraphQLMutationValidatorBundle\Formatter\Formatter();
