<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.5IVKRU1.Overblog\GraphQLBundle\Definition\Argument' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.5IVKRU1": it references class "Overblog\\GraphQLBundle\\Definition\\Argument" but no such service exists.');
