<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\BeguService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/BeguService.php';

$this->services['App\Service\BeguService'] = $instance = new \App\Service\BeguService();

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->get_ServiceLocator_YchIlgFService())->withContext('App\\Service\\BeguService', $this));

return $instance;
