<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Overblog\GraphQLBundle\CacheWarmer\CompileCacheWarmer' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/CacheWarmer/CompileCacheWarmer.php';

return $this->privates['Overblog\GraphQLBundle\CacheWarmer\CompileCacheWarmer'] = new \Overblog\GraphQLBundle\CacheWarmer\CompileCacheWarmer(($this->services['overblog_graphql.cache_compiler'] ?? $this->getOverblogGraphql_CacheCompilerService()));
