<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Lp\CatalogBundle\Controller\CatalogController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/src/Lp/Framework/LpController.php';
include_once $this->targetDirs[3].'/src/Lp/CatalogBundle/Controller/CatalogController.php';

return $this->services['App\Lp\CatalogBundle\Controller\CatalogController'] = new \App\Lp\CatalogBundle\Controller\CatalogController();
