<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.orm.lp_perl_entity_manager' shared service.

$this->services['doctrine.orm.lp_perl_entity_manager'] = $instance = \Doctrine\ORM\EntityManager::create(($this->services['doctrine.dbal.lp_perl_connection'] ?? $this->load('getDoctrine_Dbal_LpPerlConnectionService.php')), ($this->privates['doctrine.orm.lp_perl_configuration'] ?? $this->load('getDoctrine_Orm_LpPerlConfigurationService.php')));

(new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))->configure($instance);

return $instance;
