<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.doctrine.orm.lp_perl_metadata_cache' shared service.

$this->services['doctrine_cache.providers.doctrine.orm.lp_perl_metadata_cache'] = $instance = new \Doctrine\Common\Cache\ArrayCache();

$instance->setNamespace('sf_orm_lp_perl_75d4f1420d7a988ebf1bf046c412008428119cecddf6c98512519edbe343b103');

return $instance;
