<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Overblog\GraphQLBundle\EventListener\DebugListener' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/EventListener/DebugListener.php';

return $this->privates['Overblog\GraphQLBundle\EventListener\DebugListener'] = new \Overblog\GraphQLBundle\EventListener\DebugListener();
