<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\EventListener\ErrorHandlerListener' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/EventListener/ErrorHandlerListener.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Error/ErrorHandler.php';

return $this->services['Overblog\GraphQLBundle\EventListener\ErrorHandlerListener'] = new \Overblog\GraphQLBundle\EventListener\ErrorHandlerListener(new \Overblog\GraphQLBundle\Error\ErrorHandler(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), 'Internal server Error', [], false), false, true);
