<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\EventListener\ErrorLoggerListener' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/EventListener/ErrorLoggerListener.php';

return $this->services['Overblog\GraphQLBundle\EventListener\ErrorLoggerListener'] = new \Overblog\GraphQLBundle\EventListener\ErrorLoggerListener(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
