<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\Import\Importer' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Import/Importer.php';

$this->services['App\Service\Import\Importer'] = $instance = new \App\Service\Import\Importer();

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->get_ServiceLocator_YchIlgFService())->withContext('App\\Service\\Import\\Importer', $this));

return $instance;
