<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\ImportParser' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/ImportParser.php';
include_once $this->targetDirs[3].'/src/Service/TranslitService.php';
include_once $this->targetDirs[3].'/src/Service/Import/Formatter/Loader.php';

$this->services['App\Service\ImportParser'] = $instance = new \App\Service\ImportParser(new \App\Service\TranslitService(), new \App\Service\Import\Formatter\Loader());

$instance->setContainer(($this->privates['.service_locator.ychIlgF'] ?? $this->get_ServiceLocator_YchIlgFService())->withContext('App\\Service\\ImportParser', $this));

return $instance;
