<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\GraphQL\Relay\Node\NodeFieldResolver' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/GraphQL/Relay/Node/NodeFieldResolver.php';

return $this->services['Overblog\GraphQLBundle\GraphQL\Relay\Node\NodeFieldResolver'] = new \Overblog\GraphQLBundle\GraphQL\Relay\Node\NodeFieldResolver();
