<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\GraphQL\Mutation\OrderMutation' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/MutationInterface.php';
include_once $this->targetDirs[3].'/src/GraphQL/Mutation/AuthMutation.php';
include_once $this->targetDirs[3].'/src/GraphQL/Mutation/OrderMutation.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return $this->services['App\GraphQL\Mutation\OrderMutation'] = new \App\GraphQL\Mutation\OrderMutation($a, ($this->privates['Redis'] ?? $this->load('getRedisService.php')), $this, ($this->privates['App\Service\AuthenticatorService'] ?? $this->load('getAuthenticatorServiceService.php')), ($this->services['App\Service\BasketService'] ?? $this->load('getBasketServiceService.php')), $a);
