<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'overblog_graphql.command.debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Command/DebugCommand.php';

return $this->services['overblog_graphql.command.debug'] = new \Overblog\GraphQLBundle\Command\DebugCommand(($this->services['overblog_graphql.type_resolver'] ?? $this->load('getOverblogGraphql_TypeResolverService.php')), ($this->services['overblog_graphql.mutation_resolver'] ?? $this->load('getOverblogGraphql_MutationResolverService.php')), ($this->services['overblog_graphql.resolver_resolver'] ?? $this->load('getOverblogGraphql_ResolverResolverService.php')));
