<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Overblog\GraphQLBundle\EventListener\RequestFilesListener' shared service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/EventListener/RequestFilesListener.php';

return $this->services['Overblog\GraphQLBundle\EventListener\RequestFilesListener'] = new \Overblog\GraphQLBundle\EventListener\RequestFilesListener(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
