<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Redis' shared autowired service.

$this->privates['Redis'] = $instance = new \Redis();

$instance->connect($this->getEnv('REDIS_HOST'), $this->getEnv('int:REDIS_PORT'));

return $instance;
