<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\GraphQL\Mutation\UserMutation' shared autowired service.

include_once $this->targetDirs[3].'/vendor/overblog/graphql-bundle/src/Definition/Resolver/MutationInterface.php';
include_once $this->targetDirs[3].'/src/GraphQL/Mutation/AuthMutation.php';
include_once $this->targetDirs[3].'/src/GraphQL/Mutation/UserMutation.php';

$a = ($this->privates['App\Service\AuthenticatorService'] ?? $this->load('getAuthenticatorServiceService.php'));

return $this->services['App\GraphQL\Mutation\UserMutation'] = new \App\GraphQL\Mutation\UserMutation(($this->privates['Redis'] ?? $this->load('getRedisService.php')), $this, $a, ($this->services['lexik_jwt_authentication.jwt_manager'] ?? $this->load('getLexikJwtAuthentication_JwtManagerService.php')), $a);
